# values specific to testing gubbins
global:
  imagePullPolicy: Always
  images:
    tag: dev
    services: ghcr.io/aldbr/gubbins/services

developer:
  enabled: true

diracx:
  sqlDbs:
    dbs:
      LollygagDB:
